### ISSUE TITLE
Task :react-native-community_masked-view:generateDebugRFile FAILED

### ISSUE THREAD

**Issue by pouriabagheri** [react-native-masked-view/react-native-masked-view#83]
**dependency version:**     `@react-native-community/masked-view": "^0.1.10`

**error:** 
> Task :react-native-community_masked-view:generateDebugRFile FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
90 actionable tasks: 6 executed, 84 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-community_masked-view:generateDebugRFile'.
> java.util.NoSuchElementException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s

**log:** 

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'android:beta',
1 verbose cli   '--scripts-prepend-node-path=auto'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v14.4.0
4 verbose run-script [ 'preandroid:beta', 'android:beta', 'postandroid:beta' ]
5 info lifecycle mobile_react_native@1.0.1~preandroid:beta: mobile_react_native@1.0.1
6 verbose lifecycle mobile_react_native@1.0.1~preandroid:beta: unsafe-perm in lifecycle true
7 verbose lifecycle mobile_react_native@1.0.1~preandroid:beta: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Projects\mobile_react_native\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\HashiCorp\Vagrant\bin;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Program Files\Java\jdk1.8.0_211\bin;C:\Android\tools\bin\platform-tools;C:\Program Files (x86)\Yarn\bin\;C:\Users\PB\AppData\Local\Microsoft\WindowsApps;C:\Users\PB\AppData\Roaming\npm;C:\Android\tools\bin\platform-tools;C:\Users\PB\AppData\Local\Yarn\bin
8 verbose lifecycle mobile_react_native@1.0.1~preandroid:beta: CWD: C:\Users\Projects\mobile_react_native
9 silly lifecycle mobile_react_native@1.0.1~preandroid:beta: Args: [ '-c', 'npm run updateOn' ]
10 silly lifecycle mobile_react_native@1.0.1~preandroid:beta: Returned: code: 0  signal: null
11 info lifecycle mobile_react_native@1.0.1~android:beta: mobile_react_native@1.0.1
12 verbose lifecycle mobile_react_native@1.0.1~android:beta: unsafe-perm in lifecycle true
13 verbose lifecycle mobile_react_native@1.0.1~android:beta: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Projects\mobile_react_native\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\HashiCorp\Vagrant\bin;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Program Files\Java\jdk1.8.0_211\bin;C:\Android\tools\bin\platform-tools;C:\Program Files (x86)\Yarn\bin\;C:\Users\PB\AppData\Local\Microsoft\WindowsApps;C:\Users\PB\AppData\Roaming\npm;C:\Android\tools\bin\platform-tools;C:\Users\PB\AppData\Local\Yarn\bin
14 verbose lifecycle mobile_react_native@1.0.1~android:beta: CWD: C:\Users\Projects\mobile_react_native
15 silly lifecycle mobile_react_native@1.0.1~android:beta: Args: [
15 silly lifecycle   '-c',
15 silly lifecycle   'react-native run-android --variant=betaDebug --appIdSuffix=beta'
15 silly lifecycle ]
16 silly lifecycle mobile_react_native@1.0.1~android:beta: Returned: code: 1  signal: null
17 info lifecycle mobile_react_native@1.0.1~android:beta: Failed to exec android:beta script
18 verbose stack Error: mobile_react_native@1.0.1 android:beta: `react-native run-android --variant=betaDebug --appIdSuffix=beta`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
18 verbose stack     at EventEmitter.emit (events.js:315:20)
18 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:315:20)
18 verbose stack     at maybeClose (internal/child_process.js:1051:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
19 verbose pkgid mobile_react_native@1.0.1
20 verbose cwd C:\Users\Projects\mobile_react_native
21 verbose Windows_NT 10.0.19041
22 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "android:beta" "--scripts-prepend-node-path=auto"
23 verbose node v14.4.0
24 verbose npm  v6.14.5
25 error code ELIFECYCLE
26 error errno 1
27 error mobile_react_native@1.0.1 android:beta: `react-native run-android --variant=betaDebug --appIdSuffix=beta`
27 error Exit status 1
28 error Failed at the mobile_react_native@1.0.1 android:beta script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]

**Comment by pouriabagheri** [comment]
caused by some residual files in android folder.  
tried these but didn't help: 

`watchman watch-del-all && 
rm -rf $TMPDIR/react-native-packager-cache-* &&
rm -rf $TMPDIR/metro-bundler-cache-* && 
rm -rf node_modules/ 
&& npm cache clean --force &&
npm install && 
npm start -- --reset-cache`
`cd android &&./gradlew clean`

what helped was cleaning the project and removing all the generated files in android folder:
either manually or `git clean -f` in android folder
